plugins {
	id 'java'
	id 'org.springframework.boot' version '3.3.2'
	id 'io.spring.dependency-management' version '1.1.6'
	id 'maven-publish'
}

group = 'com.generic.'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenLocal()
	mavenCentral()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
         groupId = 'com.generic'
            artifactId = 'uploadservice'
            version = "0.0.1"
            from components.java
        }
    }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	compileOnly 'org.projectlombok:lombok'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.postgresql:postgresql'
	implementation 'org.apache.commons:commons-csv:1.8'
	implementation 'org.apache.poi:poi-ooxml:5.3.0'
}

tasks.named('test') {
	useJUnitPlatform()
}

bootJar {
    launchScript()
}

tasks.named("bootJar") {
    archiveClassifier = 'exec'
    enabled = true
}

tasks.named("jar") {
    archiveClassifier = ''
    enabled = true
}
