spring.application.name=uploadservice
#data source properties
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=walnut16@
#file upload properties
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
#properties of column sizes of all the entities
brandcode.column.size=2
brandname.column.size=2
creditstatus.column.size=2
customertype.column.size=2
gstntype.column.size=2
ratingtype.column.size=2
statecode.column.size=2
statename.column.size=2
